on:
    push:
        branches:
          - main
jobs:
    release:
        name: 🚀 NPM Publish
        runs-on: ubuntu-latest
        steps:
            - name: ACTIONS_ALLOW_UNSECURE_COMMANDS
              id: ACTIONS_ALLOW_UNSECURE_COMMANDS
              run: echo 'ACTIONS_ALLOW_UNSECURE_COMMANDS=true' >> $GITHUB_ENV
            - name: 📚 checkout
              uses: actions/checkout@v2.1.1
            - name: 🟢 node
              uses: actions/setup-node@v1.4.2
              with:
                  node-version: 14
                  registry-url: https://npm.pkg.github.com/
                  scope: "@subhashmahimaluri/yexaastorybook"
            - name: NPM Install
              run: npm install
            - name: 🚀 publish
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}